version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: terraform
    directories:
      - /infra/envs/dev/primary
      - /infra/envs/prod/primary
    schedule:
      interval: weekly
      day: monday
    groups:
      terraform-providers:
        patterns: ["*"]
